### PR TITLE
FEAT :  Add Functionality soo the ui accepts both xyz.com and https://xyz.com

### PR DESCRIPTION
**Pull request by kiritocode1**
## Changes 😄
---
On  */frontend/src/routes/index.tsx* 
---
```javascript
-74  : old   	
        const { newUrl } = await getShortenUrl(urlInput!.value);
-74 : new       
	const ValidUrl  = RegExp("^https://").test(urlInput!.value)? urlInput!.value : `https://${urlInput!.value}`; 
	const { newUrl } = await getShortenUrl(ValidUrl);
```
---
## Value

 - [x] Allows Users to pass ```xyz.com``` as well as ```https://xyz.com```
 - [x] Hacktoberfest Fixx for http support as well . 😄
--- 
## RULES
 Follow Code OF Conduct of the project 😄
 Does not have any Coputighted material
 Tested the application locally before merging . ❤️
---
Do let me know if some changes are needed , id love to solve some more issues and Follow this project for hacktoberfest 😃

### CODE REVIEW

**Comment by kiritocode1** [comment]
@origranot  , @GuillemPM   check this version , sorry im new to contributing 😄

**Comment by GuillemPM** [comment]
No problem! We really value your help 🔥

I'm testing your code and ValidUrl returns undefined:
image

The main problem is that variable urlInput variable is now of type `string`, but typing is missing in the file, I added it so you can see the problem:

image

As you can see a string variable doesn't have a property called value:
image

To solve this simply use the variable directly and remove those .value.

Another think I would like to point is that ValidUrl variable name should start with lowercase -> `validUrl`.
In that case the code is not that complex so please remove the comment.
And Regexp can be combined into one using separators `^https://|^http://`:
image

I will let you fix this 😁

**Comment by kiritocode1** [comment]
@GuillemPM  , heyy thanks for the comment , was really helpful ! 🚀  . Added The Requested changes please check and merge , thank you

**Comment by kiritocode1** [comment]
heyy @GuillemPM  , try this now  , working fine 😄

**Review by GuillemPM — APPROVED** [review]

**Comment by GuillemPM** [comment]
Thanks! :)

**Pull request merged**
