### PR TITLE
add preview GIF to assets and docs

### PR DESCRIPTION
**Pull request by tuhamworld**
-  Added preview GIF to assets folder on root repo
- updated the documentation to include the Preview GIF for users

### CODE REVIEW

**Comment by origranot** [comment]
@tuhamworld I think it will be better to show how it works without any delays / selecting the text and etc.
Look at my comment on the other PR: https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420

**Comment by tuhamworld** [comment]
> @tuhamworld Nice!
> 
> I think it will be better to show how it works without any delays / selecting the text and etc.
> Look at my comment on the other PR: https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420

Thank you for the feedback. Will make changes on that, and submit new PR

 P.S: I noticed the expiration drop down isn't showing on my browser. Is that intentional?

**Comment by origranot** [comment]
> > @tuhamworld Nice!
> > I think it will be better to show how it works without any delays / selecting the text and etc.
> > Look at my comment on the other PR: [#454 (review)](https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420)
> 
> Thank you for the feedback. Will make changes on that, and submit new PR
> 
> P.S: I noticed the expiration drop down isn't showing on my browser. Is that intentional?

Great 👍 

About your question, yes it's on purpose.
The expiration dropdown is only available when you are logged in with a verified account.

**Comment by tuhamworld** [comment]
> > > @tuhamworld Nice!
> > > I think it will be better to show how it works without any delays / selecting the text and etc.
> > > Look at my comment on the other PR: [#454 (review)](https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420)
> > 
> > Thank you for the feedback. Will make changes on that, and submit new PR
> > 
> > P.S: I noticed the expiration drop down isn't showing on my browser. Is that intentional?
> 
> Great 👍 
> 
> About your question, yes it's on purpose.
> The expiration dropdown is only available when you are logged in with a verified account.

Oh I didn't know about that.
Thank you for pointing it out.

Would you like the prefer to showcase the expiration too, or a simple URL shortening without delay is fine?

**Comment by origranot** [comment]
> > > > @tuhamworld Nice!
> > > > I think it will be better to show how it works without any delays / selecting the text and etc.
> > > > Look at my comment on the other PR: [#454 (review)](https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420)
> > > 
> > > 
> > > Thank you for the feedback. Will make changes on that, and submit new PR
> > > P.S: I noticed the expiration drop down isn't showing on my browser. Is that intentional?
> > 
> > 
> > Great 👍
> > About your question, yes it's on purpose.
> > The expiration dropdown is only available when you are logged in with a verified account.
> 
> Oh I didn't know about that. Thank you for pointing it out.
> 
> Would you like the prefer to showcase the expiration too, or a simple URL shortening without delay is fine?

I think it will be better to make it as simple as possible. 
I believe most of the users won't register and just use the url shortener as it it.

**Comment by tuhamworld** [comment]
> > > > > @tuhamworld Nice!
> > > > > I think it will be better to show how it works without any delays / selecting the text and etc.
> > > > > Look at my comment on the other PR: [#454 (review)](https://github.com/origranot/reduced.to/pull/454#pullrequestreview-1642702420)
> > > > 
> > > > 
> > > > Thank you for the feedback. Will make changes on that, and submit new PR
> > > > P.S: I noticed the expiration drop down isn't showing on my browser. Is that intentional?
> > > 
> > > 
> > > Great 👍
> > > About your question, yes it's on purpose.
> > > The expiration dropdown is only available when you are logged in with a verified account.
> > 
> > Oh I didn't know about that. Thank you for pointing it out.
> > 
> > Would you like the prefer to showcase the expiration too, or a simple URL shortening without delay is fine?
> 
> I think it will be better to make it as simple as possible. 
> I believe most of the users won't register and just use the url shortener as it it.


That's quite true.
Less is better. Would work on the feedback

**Comment by origranot** [comment]
@tuhamworld I would prefer to see the full flow.
The gif you did is at great speed, can you just change the short url to this repository?
Also I think it will be great to click the button and let it redirect you to this repo.

**Comment by tuhamworld** [comment]
> @tuhamworld I would prefer to see the full flow.
> The gif you did is at great speed, can you just change the short url to this repository?
> Also I think it will be great to click the button and let it redirect you to this repo.

All right. Will work on that

**Comment by tuhamworld** [comment]
I am unable to shorten the repository url.
 It's saying invalid url

**Comment by origranot** [comment]
> I am unable to shorten the repository url.
>  It's saying invalid url

Oh that's issue happens because we restrict urls that contains reduced.to (prevent recursion when redirecting)

That's another issue we can open to address this problem. Might need to strict the regex a bit.

I think you can reduce my gh profile, I pinned the repo 👏

**Comment by origranot** [comment]
@tuhamworld Also I think it better to import the gif from the file system itself (assets/usage.gif) instead of the gh link

**Comment by tuhamworld** [comment]
> > I am unable to shorten the repository url.
> >  It's saying invalid url
> 
> Oh this issue happens because we restrict urls that contains reduced.to (prevent recursion)
> 
> That's another issue we can open to address this problem. Might need to strict the regex a bit.
> 
> I think you can reduce my gh profile, I pinned the repo 👏

Oh I see.

You're right about preventing the recursion. With the new issue, you can make minor modification to allow the Github repo in the future

**Comment by tuhamworld** [comment]
> @tuhamworld Also I think it better to import the gif from the file system itself (assets/usage.gif) instead of the gh link

Will work on this

**Comment by origranot** [comment]
@tuhamworld Thank you for you contribution!
Merged!

Closes #451

**Pull request merged**
