### PR TITLE
added option to minimize sidebar #625

### PR DESCRIPTION
**Pull request by Senior-ai**
#625

### CODE REVIEW

**Comment by origranot** [comment]
Hey @Senior-ai, 

After checking this it seems it's not working.
I assumed we want to minimize it when we are using full screen right?

**Comment by Senior-ai** [comment]
@origranot thats odd.. probably doesnt work because of the recent conflicts. I'll try to fix it

**Comment by Senior-ai** [comment]
Thought I commented it earlier, but its fixed @origranot

**Comment by origranot** [comment]
@Senior-ai Hey!
It looks like it messed up the animation on the mobile view.
In addition I think we should add the toggle value to localStorage or something to make it consistent after refresh, what do you think about it?
Also it might be a good idea to change the minimize icon for larger screens.

**Comment by Senior-ai** [comment]
@origranot Hmm, that's odd - I'll try to make sure it is responsive for all type of screens first, what do you mean by changing the minimize icon? just enlarging it or changing it completely ?

regarding keeping it in localStorage, that's actually a good idea that I didn't think about. I'll work on it tomorrow

**Comment by origranot** [comment]
> @origranot Hmm, that's odd - I'll try to make sure it is responsive for all type of screens first, what do you mean by changing the minimize icon? just enlarging it or changing it completely ?
> 
> regarding keeping it in localStorage, that's actually a good idea that I didn't think about. I'll work on it tomorrow

@Senior-ai Hey champ!

What I meant is that I think we should change the icon to an arrow icon or something to make it more clear that the sidebar can be minimized.
In addition,I found a really good example of how I think it should look (on desktop screens)
https://www.cssscript.com/demo/smooth-collapsible-sidebar-navigation/

On mobile screens I think we should keep it as is.

**Pull request closed without merging**
