### PR TITLE
✨ feat: input is focused on page load

### PR DESCRIPTION
**Pull request by jessej-samuel**
The input now gets auto-focused on page load

### CODE REVIEW

**Comment by jessej-samuel** [comment]
@origranot I've set the input to focus on page load. Where should I add the event listener for `/` ? 😅

**Comment by origranot** [comment]
> @origranot I've set the input to focus on page load. Where should I add the event listener for `/` ? 😅

We don't really have a strict architecture at the moment.

I think you should probably put it somewhere in ```shortener-input``` component

**Comment by jessej-samuel** [comment]
fixes #328

**Comment by jessej-samuel** [comment]
Hey, I was not able to figure out where to add the event listener for `/`. So I just made it to be autofocused on page load.

**Review by origranot — CHANGES_REQUESTED** [review]
I would prefer to add the listener instead of the autoFocus.

You can add it into the shortener-input component.

**Pull request closed without merging**
