### PR TITLE
Changed README GIFs

### PR DESCRIPTION
**Pull request by amittri1025**
Update README GIFs as specified in issue  #204

### CODE REVIEW

**Comment by origranot** [comment]
Hey, do you mind fix the size of the gif to be the same as the old one?

**Comment by amittri1025** [comment]
the size looks nice as of now

do you want me to reduce the quality of gif?

**Comment by origranot** [comment]
@amittri1025 No, don't reduce the quality of the gif, try to maintain the same aspect ratio as the old gif.
You can cut the waves from the screenshot if needed, the goal is making the gif  fit better on the readme file.

**Comment by origranot** [comment]
@amittri1025 Do you mind change the size of the gif? 💯

**Pull request closed without merging**
