### PR TITLE
#292 Style the tooltip component

### PR DESCRIPTION
**Pull request by Riyadutt**
Fix for #292

### CODE REVIEW

**Comment by Riyadutt** [comment]
thanks, will have a look and make the changes.

**Comment by Riyadutt** [comment]
changes done, have a look.

**Comment by Riyadutt** [comment]
changes are done, have a look. @GuillemPM @origranot

**Comment by GuillemPM** [comment]
Thanks, I still think it's not following the correct theming rules.

What do you think about using the default theme variables?
Usually tooltip background should be neutral, as well as the text color.

Those variables are --n (neutral) and --nc (neutral-color), they are provided by DaisyUI so you can directly use them.

Tooltip.css:
```css
.r-tooltip {
  background-color: hsl(var(--n));
  color: hsl(var(--nc));
}

.r-tooltip > span {
  background-color: hsl(var(--n));
}
```

Tooltip.tsx:
```ts
return (
    <div
      className={`${
        classes.container
      } r-tooltip absolute whitespace-nowrap rounded py-[6px] px-4 text-sm font-semibold ${
        store.hidden ? 'hidden' : ''
      }`}
    >
      <span class={`${classes.span} absolute -z-10 h-2 w-2 rotate-45 rounded-sm`}></span>
      {label}
    </div>
  );
```

Since tooltip class is already created by daisyUI, we must create our own class, that's why I call it r-tooltip (r from reduced) since it's our own tooltip component.

Now we don't need any custom variable in global.css

# Demo
### Dark theme
image

### Light theme
image


If we change the theme in the future it will still follow the color guidelines from the selected theme.

Could you apply these changes?

**Comment by Riyadutt** [comment]
made the suggested changes.

**Comment by Riyadutt** [comment]
> Please fix the format of the files before I merge it

fixed, does the action run automatically ?

**Pull request merged**
