### PR TITLE
Fix/scroll Issue of Scrolling

### LINKED ISSUE #515: Homepage not scrollable when more content is loaded
### Description

The homepage is not scrollable when a link is generated; instead, it just pushes the content and takes its place. Additionally, when a QR code is generated, only a small part is visible.

### Screenshots

InkedScreenShot Tool -20231015221731

InkedScreenShot Tool -20231015221602

### Additional information

video demonstration

reduced to bug (1)

### PR DESCRIPTION
**Pull request by khanjanSanghavi**
fixes #515 

This pr fixes the Scrolling issue 
now user can scroll through the page with fix navbar

video Demonstration: 
https://github.com/origranot/reduced.to/assets/75749613/e162d37f-30cf-40f8-81a3-a11954e2e96a

### CODE REVIEW

**Comment by origranot** [comment]
@khanjanSanghavi Hey, thanks for your time!
Please take a look at the Expiration Time block at your video. (seems like it's moving).
What do you think?

**Comment by khanjanSanghavi** [comment]
Yaa The time block is not moving will fix it in a day

**Comment by khanjanSanghavi** [comment]
@origranot fixed the issue of Expiration Time block 

https://github.com/origranot/reduced.to/assets/75749613/8601ad4f-d2e1-432f-a274-19edafeb1b38

**Comment by origranot** [comment]
@khanjanSanghavi Hey!

This is not in the correct position, please take a look at the current placement:
image
image

**Comment by khanjanSanghavi** [comment]
Hope This is final fix
@origranot Thankyou so much for your patience though

**Comment by khanjanSanghavi** [comment]
https://github.com/origranot/reduced.to/assets/75749613/99bc9873-8017-4f53-86cc-5518bce576ff

**Comment by origranot** [comment]
@khanjanSanghavi This looks much better!

Any chance we can put it on the same line?

**Comment by khanjanSanghavi** [comment]
@origranot  Yaa Done 

Screenshot (83)

I am so grateful to have my first mentor like you 
Thanks for being soo patient

**Comment by origranot** [comment]
@khanjanSanghavi Looks great!

**Pull request merged**
