### PR TITLE
New Favicon (Issue #297)

### PR DESCRIPTION
**Pull request by owengaspard**
Addresses issue #297 

I have designed a new favicon for the app.

mstile-144x144

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]
LGTM!

**Comment by origranot** [comment]
@owengaspard Nice idea!

I would prefer to make the brackets a bit smaller and add more spacing.
Also maybe play with the colors a bit, make it fit to our theme.

**Comment by origranot** [comment]
@owengaspard Hey!

The favicon looks great!
I didn't understand why you created a favicon for each device?

What do you think about keeping only 1 .ico file?

**Comment by origranot** [comment]
https://github.com/origranot/reduced.to/pull/335

**Pull request closed without merging**
