### PR TITLE
Added a unit test for ShortenerController

### PR DESCRIPTION
**Pull request by professorjrod**
I made a generic mocker for the controller. It can take in an instance token and return a mock implementation. I was having trouble figuring out how to mock the dependencies so I just left it as an undefined check.

### CODE REVIEW

**Comment by origranot** [comment]
@professorjrod 👋 

Thank you for the PR!

Don't mock the service like this.
You can use __mocks__ folder with jest.
For example: https://stackoverflow.com/questions/68885078/jest-mock-multiple-services-in-one-test-file-nest-js

**Review by origranot — CHANGES_REQUESTED** [review]
Please use manual mocks.

**Comment by origranot** [comment]
@professorjrod Any update?

**Comment by professorjrod** [comment]
I'll work on it tomrrow

**Comment by professorjrod** [comment]
any update on this pr?

**Comment by origranot** [comment]
@professorjrod 👋 

Nice work, you can use __mocks__ folder instead of override provider.

Please keep the test service/controller on the same folder as the original service or controller.

Do you mind fix those changes before we accept the pr?

**Comment by origranot** [comment]
@professorjrod Hey, are you still working on it?

**Comment by professorjrod** [comment]
Yeah I am just got busy.

**Comment by professorjrod** [comment]
@origranot Can you give me some examples of using mocks folder? I need to be pointed in the right direction.

**Comment by origranot** [comment]
> @origranot Can you give me some examples of using mocks folder? I need to be pointed in the right direction.
It's called manual mocks, https://jestjs.io/docs/manual-mocks

**Pull request closed without merging**
