### PR TITLE
Authjs

### PR DESCRIPTION
**Pull request by barel-mishal**
This PR offers integration with Auth.js, enabling sign-in through Google and GitHub providers. 

I've successfully implemented error messages for unsuccessful login attempts and managed to handle both sign-in and sign-up using Auth.js. It's important to note that the GitHub provider may sometimes not share the email address. Consequently, sign-in attempts using GitHub may fail if the email is not provided, as it is essential for our schema in the database. 

Additionally, it's important to mention that this PR does not interfere with the existing methods of signing in or registering using a username, email, and password; it simply adds an additional way to sign in through providers.

### CODE REVIEW

**Comment by origranot** [comment]
Hey @barel-mishal 
After migrating the whole repo to nx we need to modify this PR.
Do you mind fix the conflicts?

**Comment by barelmishal** [comment]
Hi, yes no problem I will have this updated. Thanks!

**Comment by barel-mishal** [comment]
Hi, yes no problem I will have this updated. Thanks!

**Comment by origranot** [comment]
Done in https://github.com/origranot/reduced.to/pull/595

**Pull request closed without merging**
