### PR TITLE
Updated DaisyUI to 3.0 and fixed breaking changes.

### PR DESCRIPTION
**Pull request by izdotnet**
Updated to the latest version of DaisyUI (3.0.20)

### CODE REVIEW

**Review by origranot — CHANGES_REQUESTED** [review]
@izdotnet Nice job!

After testing the PR I can see there are still some changes the new version causes.

Buttons are not the same as the last version:
image

Input is with the wrong bg color:
image

Looks like badges are not in the same color:
image

Drawer is not working properly:
image

**Comment by izdotnet** [comment]
Thanks for the review.

I will work on those issues.

**Comment by izdotnet** [comment]
Pushed another commit to address the mentioned issues.

Waiting for you review.

**Review by origranot — CHANGES_REQUESTED** [review]
Hey, @izdotnet I saw the changes, everything looks perfect!

There are some tiny changes I noticed:

Color of the text inside buttons:
image

The buttons at the dashboard drawer should be primary and a bit bigger.
image

Another thing with the drawer, when we close it we don't have the animation.
Also when it visible in mobile view it looks weird:
image

**Comment by izdotnet** [comment]
Pushed another commit to address the font color, drawer size, drawer links size.

Drawers in DaisyUI has only opening animation by default as demonstrated in the official documentation.

**Comment by origranot** [comment]
Hey @izdotnet,

The drawer seems to not working at all.

**Pull request merged**
