### PR TITLE
Navbar overlapping ui bug fixed

### PR DESCRIPTION
**Pull request by Debangan202Ok**
simplistic changes make perfect.
Hopefully Issue no. #473 fixed.

### CODE REVIEW

**Comment by origranot** [comment]
@Debangan202Ok Hey,

What about dark theme? 🕶️

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok Hey,
> 
> What about dark theme? 🕶️

yeah! just give a minute

**Comment by Debangan202Ok** [comment]
@origranot Now Check #476

**Comment by origranot** [comment]
@Debangan202Ok 

The navbar looks great!
What about the sidebar? when scrolling to the bottom of the page it's overlapping aswell.

image

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok 
> 
> The navbar looks great!
> What about the sidebar? when scrolling to the bottom of the page it's overlapping aswell.
> 
> image
> 

Give me a minute 🥲🚀

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok 
> 
> The navbar looks great!
> What about the sidebar? when scrolling to the bottom of the page it's overlapping aswell.
> 
> image
> 

@origranot, this issue is not related to the navbar; it's happening because of the container separation in the footer. But thank you for pointing it out. I will fix it for sure.

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok Hey!
> Are you planning on fixing it this PR, or do you think we should do it as a different issue?

@origranot at this time what i done merge it.for now it take as a different issue. Exams on my head so at this I'm unable do it. Sorry for inconvenience

**Pull request merged**
