### PR TITLE
Added a Dark Light Button and Github star button

### PR DESCRIPTION
**Pull request by amittri1025**
[eb575e66-6c26-425d-b8f8-6fd2d57d0432.webm](https://user-images.githubusercontent.com/74503582/194880741-89351729-0c09-4ec5-a097-144810e0d288.webm)

### CODE REVIEW

**Comment by origranot** [comment]
@amittri1025 👋 

The dark mode toggle looks amazing.
Did you noticed we migrated into Qwik framework?

We are using Typescript on our front. do you mind to update the PR?

**Review by origranot — CHANGES_REQUESTED** [review]
@amittri1025 👋

The dark mode toggle looks amazing.
Did you noticed we migrated into Qwik framework?

We are using Typescript on our front. do you mind to update the PR?

**Comment by origranot** [comment]
@amittri1025 Any update?

**Comment by amittri1025** [comment]
I do not know how to use Qwik Framework and TypeScript.

**Comment by origranot** [comment]
> I do not know how to use Qwik Framework and TypeScript.

Unfortunately, we can't merge it without you migrate it into Qwik.

It's similar to React, If you still want to handle this issue I will wait for a commit from you.

Otherwise I would like to assign someone else for this issue.

**Comment by amittri1025** [comment]
Ok I will try learning Qwik Framework and will update the PR

**Comment by amittri1025** [comment]
One thing, I want to ask, Is it important to get assigned to work on any PR/issue or you can directly work and open a PR

**Comment by origranot** [comment]
@amittri1025 Hey, we did push major changes.

Do you mind update your commit?

Thanks!

**Comment by GuillemPM** [comment]
Please follow DaisyUI theme guidelines instead of creating css classes for dark and light.
https://daisyui.com/docs/themes/
https://daisyui.com/theme-generator/

**Comment by origranot** [comment]
@amittri1025 any update?

**Pull request closed without merging**
