### PR TITLE
Feature: Display email on verification page

### PR DESCRIPTION
**Pull request by icepick4**
Closes: https://github.com/origranot/reduced.to/issues/532

Hey!

I displayed email used by the user on the verification page.

To do that I added a new field `email` to the method : `checkVerification` then I get it on the front side and display on the component, see : 

image

(I am not sure about the sentence tell me if it needs some changes.

### CODE REVIEW

**Review by origranot — CHANGES_REQUESTED** [review]
@icepick4 Hey,

Nicely done!
I don't think we have to change the backend and return the email itself.
Instead we can read the email from the cookie itself, what do you think?

```js
const user = useGetCurrentUser();

// Get the email
user.value.email
```

**Comment by icepick4** [comment]
> @icepick4 Hey,
> 
> Nicely done! I don't think we have to change the backend and return the email itself. Instead we can read the email from the cookie itself, what do you think?
> 
> ```js
> const user = useGetCurrentUser();
> 
> // Get the email
> user.value.email
> ```

Hi! 

Yeah you're right, I changed that and it uses directly the cookie now !

**Review by origranot — CHANGES_REQUESTED** [review]
Why using a store at all?

You can just use the userCtx.

**Comment by icepick4** [comment]
> Why using a store at all?
> 
> You can just use the userCtx.

okok I see, I changed that. Thank you

**Review by origranot — APPROVED** [review]
Nice!

**Comment by origranot** [comment]
@icepick4 Hey!

Seems like the prettier has failed.
Can you please run `npx nx format:write` and push the changes?

**Comment by icepick4** [comment]
Done :+1:

**Comment by origranot** [comment]
@icepick4 What a champ!
Great job 💯

**Pull request merged**
